DROP TABLE IF EXISTS TBL_USER;
 
CREATE TABLE TBL_USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
   name VARCHAR(250) NOT NULL,
  user_name VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL ,
  email VARCHAR(250) DEFAULT NULL
);