CREATE USER IF NOT EXISTS SA SALT '2abe13e86456fb2c' HASH '17a39a470ded61cec2ac3eb709c343ee61a86f4ef2178661446dda1ba6b89cda' ADMIN;
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 2;
CREATE MEMORY TABLE PUBLIC.ROLE( 
    ROLE_ID INTEGER NOT NULL, 
    ROLE VARCHAR(255) 
);
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ROLE_ID);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;
CREATE MEMORY TABLE PUBLIC.USER_ROLE( 
    USER_ID INTEGER NOT NULL, 
    ROLE_ID INTEGER NOT NULL 
);
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(USER_ID, ROLE_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_ROLE;
CREATE MEMORY TABLE PUBLIC.USER( 
    USER_ID INTEGER NOT NULL, 
    ACTIVE INTEGER, 
    EMAIL VARCHAR(255), 
    LAST_NAME VARCHAR(255), 
    NAME VARCHAR(255), 
    PASSWORD VARCHAR(255), 
    USER_NAME VARCHAR(255) 
);
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY(USER_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.FK859N2JVI8IVHUI0RL0ESWS6O FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(USER_ID) NOCHECK;
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.FKA68196081FVOVJHKEK5M97N3Y FOREIGN KEY(ROLE_ID) REFERENCES PUBLIC.ROLE(ROLE_ID) NOCHECK;